      PROGRAM D1141
       COMMON /PARAMS/ACC,NDIM,NSUB,ITER
       COMMON/STORAG/ MA(20),MB(20),MC(20),XA(20),XB(20),XC(20),XD(20)
       COMMON/STORA/LR,R(5000)
         COMMON/OPTION/IPRINT,ICONV,IRESET
          COMMON/RANDOM/NSHOTS,RESTAR
      COMMON/INTERN/NOUT,FACTOR,LEVEL,ALFA,BETA,GAMMA,DELTA,NMIN
       EXTERNAL EXAMPL
       ACC=1.
       NDIM=2
       NSUB=100
       ITER=5
       CALL STD114
      CALL RIWIA(EXAMPL)
       END
      FUNCTION EXAMPL(Q)
      DIMENSION Q(20)
       EXAMPL=Q(1)*(Q(2)**2)
       END
*EXECUTE
*
*
