      PROGRAM D129
C    TEST FOR D127 , D128 , D129
      EXTERNAL AINT, CKGAUS,CSIMPS
      COMPLEX SUM,AINT,ERROR,ABSSUM,VS
      DIMENSION ZS(100), VS(100,2)
      CALL ZSIN (1.,100,ZS)  $  PRINT 2
      A=0.  $  B=3.  $  FRQ=90.  $  EPS=1.E-8
      CALL CELON (CKGAUS,A,B,FRQ,0.,AINT,ZS,99,VS,EPS,SUM,ERROR,-1.)
      SUMR=SUM  $  SUMJ=(0.,-1.)*SUM  $  ER=ERROR  $  EJ=(0.,-1.)*ERROR
      ASR=ABS(SUMR)  $  ASJ=ABS(SUMJ)
      PRINT 1, SUMR,SUMJ,ER,EJ,ASR,ASJ
      CALL CKGAUS (A, B,  AINT,1.E-8,SUM,ERROR,ABSSUM)
      SUMR=SUM  $  SUMJ=(0.,-1.)*SUM  $  ER=ERROR  $  EJ=(0.,-1.)*ERROR
      ASR=ABSSUM  $  ASJ=(0.,-1.)*ABSSUM
      PRINT 1, SUMR,SUMJ,ER,EJ,ASR,ASJ
      CALL CSIMPS (A, B,  AINT,1.E-8,SUM,ERROR,ABSSUM)
      SUMR=SUM  $  SUMJ=(0.,-1.)*SUM  $  ER=ERROR  $  EJ=(0.,-1.)*ERROR
      ASR=ABSSUM  $  ASJ=(0.,-1.)*ABSSUM
      PRINT 1, SUMR,SUMJ,ER,EJ,ASR,ASJ
      CALL CELON (CSIMPS,A,B,FRQ,0.,AINT,ZS,99,VS,EPS,SUM,ERROR,-1.)
      SUMR=SUM  $  SUMJ=(0.,-1.)*SUM  $  ER=ERROR  $  EJ=(0.,-1.)*ERROR
      ASR=ABS(SUMR)  $  ASJ=ABS(SUMJ)
      PRINT 1, SUMR,SUMJ,ER,EJ,ASR,ASJ
      STOP
 1    FORMAT (3X,6HRE(I)=,E16.9,2X,6HIM(I)=,E16.9,3X,6HRE(E)=,E9.2,2X,
     * 6HIM(E)=,E9.2, 3X,7HRE(AI)=,E16.9,2X,7HIM(AI)=,E16.9)
  2   FORMAT(//50X,19HTEST D127,D128,D129//12X,3HSUM,18X,12H(0.,-1.)*SUM
     1 ,12X,5HERROR,6X,14H(0.,-1.)*ERROR,8X,5H/SUM/,16X,14H(0.,-1.)*ERRO
     2R///)
      END
      COMPLEX FUNCTION AINT (X)
      SX=SIN(90.*X)
      GSX=1000.*SX/(1.+X)
      ESX=1000.*SX/(1.+X**2)
      AINT=GSX+(0.,1.)*ESX
      RETURN
      END
      SUBROUTINE ZSIN (FACTOR,NZ,ZERO)
      DIMENSION ZERO(NZ)
      DATA (PI=3.1415926536)
      KS=1  $  AS=ABS(FACTOR)
      IF (FACTOR.LT.0.) KS=NZ
      DO 1 M=1,NZ
      AM=M-KS
 1    ZERO(M)=AM*PI*AS
      RETURN
      END
*EXECUTE
*
*
