      PROGRAM D130
      EXTERNAL KGAUSS,ERSIMP,RJAD,FEX
      DIMENSION ZERO(50 ), V(50 ,2),ZFN(50 )
      DATA (EPS=1.E-9 ),(NZ=30 ) ,(EF=2.)
      PRINT 1
 1    FORMAT (1H1)
      PRINT 2
 2    FORMAT (5X,49HINTEGRAL (2.*SIN(100.*X)/X*DX )=3.1415926536     /5X
     *,49(1H-))
      PRINT 3
 3    FORMAT (20X,21HINTEGRAL SUMIR-KGAUSS/20X,21(1H-))
      CALL ZSIN (1.,NZ,ZERO)
      CALL SUMIR (KGAUSS,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
 4    FORMAT (1X,3HNZ=,I3,5X,4HSUM=,E18.11,5X,6HERROR=,E9.2,5X,2HN=,
     *I3,5X,2HK=,I3,5X,4HEPS=,E9.2/)
      NZ=10
      CALL SUMIR (KGAUSS,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
      NZ=30
      PRINT 5
 5    FORMAT (20X,21HINTEGRAL SUMIR-ERSIMP/20X,21(1H-))
      CALL SUMIR (ERSIMP,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
      PRINT 6
 6    FORMAT (20X,23HSERIE   SERIE   SERIE  /20X,23(1H-))
      IEF=EF  $  PRINT 7, IEF
 7    FORMAT (1X,42HS(Z)=(1+Z+Z**2+Z**3+...)= 1/(1-Z) , SUM=S(,I1,1H) )
      CALL NROW (1.,50 ,ZFN)
      CALL SUMIR (RJAD,0.,1.,0.,EF,ZFN,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
      END
      SUBROUTINE RJAD (Z1,Z2,EF,AEPS,R,ERR,AR)
      R=EF**Z1
      ERR=0.  $  AR=ABS(R)
      RETURN
      END
      FUNCTION FEX (X)
      FEX=200.
      IF (X.NE.0.) FEX=2.*SIN(100.*X)/X
      RETURN
      END
      SUBROUTINE ZSIN (FACTOR,NZ,ZERO)
      DIMENSION ZERO(NZ)
      DATA (PI=3.1415926536)
      KS=1  $  AS=ABS(FACTOR)
      IF (FACTOR.LT.0.) KS=NZ
      DO 1 M=1,NZ
      AM=M-KS
      AM=M-KS
 1    ZERO(M)=AM*PI*AS
      RETURN
      END
      SUBROUTINE NROW (STEP,NR,ROW)
      DIMENSION ROW(NR)
      KS=1  $  AS=ABS(STEP)
      IF (STEP.LT.0.) KS=NR
      DO 1 M=1,NR
      AM=M-KS
 1    ROW(M)=AM*AS
      RETURN
      END
*EXECUTE
*
*
