      PROGRAM D131
      COMPLEX SUM, ERROR, FEX, V
      EXTERNAL CKGAUS,CSIMPS,RJAD,FEX
      DIMENSION ZERO(50 ), V(50 ,2),ZFN(50 )
      DATA (EPS=1.E-9 ),(NZ=20 )
      PRINT 1
 1    FORMAT (1H1)
      PRINT 2
 2    FORMAT (5X,36HINTEGRAL ( (2.,2.)*SIN(100*X)/X*DX )/5X,36(1H-))
      PRINT 3
 3    FORMAT (20X,22HINTEGRAL CSUMIR-CKGAUS/20X,22(1H-))
      CALL ZSIN (1.,NZ,ZERO)
      CALL CSUMIR(CKGAUS,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
 4    FORMAT (1X,3HNZ=,I3,5X,4HSUM=,2E20.11,5X,6HERROR=,2E10.2,5X,2HN=,
     *I3,5X,2HK=,I3,5X,4HEPS=,E9.2/)
      NZ=10
      CALL CSUMIR(CKGAUS,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
      NZ=20
      PRINT 5
 5    FORMAT (20X,22HINTEGRAL CSUMIR-CSIMPS/20X,22(1H-) )
      CALL CSUMIR(CSIMPS,0.,100.,0.,FEX,ZERO,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
 77   CONTINUE
      PRINT 6
 6    FORMAT (20X,21HSERIE   SERIE   SERIE  /20X,21(1H-))
      PRINT 7
 7    FORMAT (5X,51HS(Z)=(1+Z+Z**2+Z**3+...)= 1/(1-Z) , SUM=S( (1.,1.)))
      CALL NROW (1.,NZ ,ZFN)
      CALL CSUMIR(RJAD,0.,1.,0.,FE,ZFN,NZ,V,EPS,SUM,ERROR,N,K)
      PRINT 4, NZ,SUM,ERROR,N,K,EPS
      END
      SUBROUTINE RJAD (Z1,Z2,EF,AEPS,R,ERR,AR)
      COMPLEX EF,R,ERR,AR
      M=Z1  $  R=(1.,1.)**M
      ERR=0.  $  RR=R  $  RJ=(0.,-1.)*R
      AR=ABS(RR)+(0.,1.)*ABS(RJ)
      RETURN
      END
      COMPLEX FUNCTION FEX (X)
      FEX=(200.,200.)
      IF (X.EQ.0.) RETURN
      FEX=(2.,2.)*SIN(100.*X)/X
      RETURN
      END
      SUBROUTINE ZSIN (FACTOR,NZ,ZERO)
      DIMENSION ZERO(NZ)
      DATA (PI=3.1415926536)
      KS=1  $  AS=ABS(FACTOR)
      IF (FACTOR.LT.0.) KS=NZ
      DO 1 M=1,NZ
      AM=M-KS
 1    ZERO(M)=AM*PI*AS
      RETURN
      END
      SUBROUTINE NROW (STEP,NR,ROW)
      DIMENSION ROW(NR)
      KS=1  $  AS=ABS(STEP)
      IF (STEP.LT.0.) KS=NR
      DO 1 M=1,NR
      AM=M-KS
 1    ROW(M)=AM*AS
      RETURN
      END
*EXECUTE
*
*
