      PROGRAM D151
C     EXAMPLE DRIVER PROGRAM FOR DIVON4 (D151).
C
      REAL XMINUS(4),XPLUS(4)
      N=4
      DO 10 I=1,N
      XMINUS(I)=0.0
      XPLUS(I)=10.0
  10  CONTINUE
      ERROR=0.005
      CALL DIVON (N,XMINUS,XPLUS,ERROR,100000,FINT,ERRIN)
      END

      DOUBLE PRECISION FUNCTION DFUN (N,X)
      DOUBLE PRECISION X(N)
      DFUN=0.0D0
      DO 10 I=1,N
      DFUN=DFUN-X(I)
   10 CONTINUE
      DFUN=DEXP(DFUN)
      RETURN
      END
*CALL ALLMEMORY
*EXECUTE
*
*
