      PROGRAM E410
C        THIS PROGRAM TESTS CPSC - COMPLEX POWER SERIES COEFFICIENTS - B
C        FINDING THE EXPANSION OF F = 1/Z AROUND (0.4,0.3) FOR THE NUMBE
C        OF COEFFICIENTS WANTED EQUAL TO 6,12,25 AND 51. THE FAST FOURIE
C        TRANSFORMS WILL THEN BE RUN OVER 8,16,32 AND 64 POINTS RESPECTI
C        THE COEFFICIENTS OBTAINED ARE COMPARED WITH -(-1.6,1.2)**N WHIC
C        THE EXACT ANSWER. THE LARGEST RELATIVE ERRORS AND THE LARGEST
C        QUOTIENTS BETWEEN ACTUAL AND ESTIMATED ERRORS IN THE FOUR CASES
C        ARE PRINTED.
C
      DIMENSION NR(4),RS(51),ER(51)
      COMPLEX Z,ZR,RS
      EXTERNAL F
      DATA NR/6,12,25,51/
      DO 20 IR=1,4
      N = NR(IR)
      Z=CMPLX(.4,.3)
      CALL CPSC(F,Z,N,RS,ER)
      PRINT 1,N,(RS(I),I=1,N)
      PRINT 2,(ER(J),J=1,N)
      ZR=(-1.,0.)
      RM=0.
      DO 10 I=1,N
      ZR=ZR*CMPLX(-1.6,1.2)
      R=CABS(RS(1)-ZR)
      RL=R/CABS(ZR)
 10   IF(RL.GT.RM)RM=RL
  20  PRINT 30,N,RM
  1   FORMAT(///1X,2HN=,I2//5X,3HRS=/(5X,6E18.10/))
  2   FORMAT(/3X,3HER=/(3X,6E18.10)/)
  30  FORMAT(/5X,2HN=,I2 ,5X,3HRM=,E10.2)
      END
      COMPLEX FUNCTION F(Z)
      COMPLEX Z
      F=CMPLX(1.,0.)/Z
      RETURN
      END
*EXECUTE
*
*                                                                    A
