*       This test fails when loading: OTCYTCTBYET  MINSTA MINISO MINEND
      PROGRAM M251
      COMMON/MINIFL/IFLAG
      DIMENSION MCAR(14,1000),MERR(1000)
      CALL MINCOD(MCAR,MERR,1000)
      IFLAG=1
      CALL MINCOD(MCAR,MERR,1000)
      STOP
      END
*EXECUTE
*
*
